blue-yonder/tsfresh

- tsfresh/examples/robot_execution_failures.py
In case of insufficient permissions, a RuntimeError including
a description of the problem and possible solutions is raised.
This resolves issue #16
> Check file permissions before attempting to write

- tests/test_feature_significance.py
For https://github.com/blue-yonder/tsfresh/issues/8
This fixes the use of xrange function in tests/test_feature_significance.py
xrange has been removed in Python 3 and range in Python 3 is now the same as
xrange in Python 2.7.x (with a caveat that there is evidence that certain
Python 3 range usages are NOT a fast as Python 2.7.x xrange).
Searching the code xrange is only used in tests/test_feature_significance.py,
however that said in the master version there are only 2 calls to xrange and in
the i8_add_python3_support branch version there were 8, so @MaxBenChrist I am
not certain if there was a specific intention there.
All tests pass on Python 3.5.2, without handling the builtins in Python 2.7.x it
is not possible to say that if these tests pass on 2.7.x, it is a small change
and range …
> Changed xrange to range

- tests/feature_extraction/test_feature_calculations.py
- tests/feature_extraction/test_settings.py
- tests/feature_extraction/test_ts_features.py
- tests/fixtures.py
- tests/test_feature_significance.py
- tests/transformers/test_feature_augmenter.py
In tests/fixtures.py csort does not work on 3.5 as range has changed type from
list to class in py3 - fixed and tested ok on 2.7 and 3.5
Implications of the type change of range from list to class in py3 could have
some deeper ramifications - https://github.com/blue-yonder/tsfresh/search?p=2&q=range
```
tests/test_relevant_feature_extraction.py:25:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <tests.test_relevant_feature_extraction.RelevantFeatureExtractionTestCase testMethod=test_functional_equality>
def create_test_data_sample_with_target(self):
"""
Small test data set with target.
:return: timeseries df
:return: target y which is the mean of each sample's timeseries
"""
cid = np.repeat(range(50), 3)
>       csort = range(3) * 50
E …
```
> csort range py3 compatible

- tests/utilities/test_dataframe_functions.py
- tsfresh/utilities/dataframe_functions.py
at the moment if one does 
```
X_ts = extract_features(ts, column_id='id', column_value="value", feature_extraction_settings=extraction_settings)
```
one gets features named `feature__mean` instead of `value__mean`. this does not follow our own naming convention.
> always use value column name as feature name

- docs/index.rst
- docs/text/parallelization.rst
- requirements.txt
- tests/feature_extraction/test_extraction.py
- tests/feature_extraction/test_ts_features.py
- tests/feature_selection/test_feature_selectors.py
- tsfresh/feature_extraction/extraction.py
- tsfresh/feature_extraction/settings.py
- tsfresh/feature_selection/feature_selector.py
- tsfresh/feature_selection/settings.py
The PR is not ready for a merge. I opened it to facilitate the discussion of the introduced changes. Please comment!
Here's what I did: I extracted the parallel calculation of the features and added two functions for this purpose. One works just as before, parallelising the calculation per time series kind. The other additionally parallelizes per sample.
As the parallelization per sample introduces significant overhead on large data sets with several time series per sample, we should offer both options. Therefore I introduced a new optional argument to the extract_features function. A rule-of-thumb is used to determine the default strategy.
TODO:
- ~~Ensure test coverage for both parallel extract functions~~
- ~~Add documentation discussing the tradeoffs involved in the two options~~
- …
> Improve parallelization

- tests/baseline/tsfresh_features_test.py
the snapshot tests on travis are failing because it gets a dirty version tag (0.4.0+ng7e4c397.dirty).
Travis compares the calculated features to a non existing baseline file. this pr will solve it
> Fix travis

- tsfresh/feature_extraction/settings.py
Added the missing parentheses in the docstring examples as referred in https://github.com/blue-yonder/tsfresh/issues/130#issuecomment-269128313
> Correct docstring exmples #130

- docs/index.rst
- docs/text/feature_extraction_settings.rst
- docs/text/how_to_add_custom_feature.rst
- notebooks/compare-runtimes-of-feature-calculators.ipynb
- notebooks/human_acitivity_recognition_example.ipynb
- notebooks/pipeline_example.ipynb
- notebooks/robot_failure_example.ipynb
- tests/feature_extraction/test_extraction.py
- tests/feature_extraction/test_settings.py
- tests/test_relevant_feature_extraction.py
- tests/transformers/test_feature_augmenter.py
- tests/transformers/test_relevant_feature_extractor.py
- tsfresh/convenience/relevant_extraction.py
- tsfresh/feature_extraction/__init__.py
- tsfresh/feature_extraction/extraction.py
- tsfresh/feature_extraction/settings.py
- tsfresh/transformers/feature_augmenter.py
- tsfresh/transformers/relevant_feature_augmenter.py
I renamed `calculation_settings_mapping` to `para_map`. 
I do not like the long name, which result in a java like beasts such as  `default_calculation_settings_mapping` or `kind_to_calculation_settings_mapping`.
We should have a catchy, short (<10 character) name for the extraction settings. We are breaking our public API, so now is the time to change it.
> renaming of settings classes and arguments for extract_features

- tests/transformers/test_feature_selector.py
- tsfresh/transformers/feature_selector.py
* FeatureSelection().relevant_features is a DataFrame which contains the p-values of the selected features. 
* FeatureSelection().relevant_features.index holds the column names of the selected features.
> Provide p-values of selected features

- tests/utilities/test_dataframe_functions.py
- tsfresh/transformers/relevant_feature_augmenter.py
- tsfresh/utilities/dataframe_functions.py
Improve performance of the functions:
- utilities.dataframe_function.get_range_values_per_column(df)
- utilities.dataframe_function.impute(df_impute)
More specifically: apply the impute function directly on numpy array to improve computation time.
Now the impute function runs in 109ms (60 samples, 14256 features (or columns) ).
Note: I did not impoved the performance of impute_dataframe_range(...) since it would have been to much of a hassle to implement all the checks in that function, e.g. in case the min/max/median values of each columns are not present. In our case we call the get_range_values_per_column just before so these checks are not necessary.
So I just reimplemented the function impute_dataframe_rage directly in the impute function. This is less modular. Maybe you could pack …
> Improve performance of the impute function.

- tests/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
Changed `sum_of_reoccurring_values` to only sum non-unique values once and added `sum_of_reoccurring_data_points` to sum non-unique values by their number of appearance:
I think the difference is best illustrated by example:
sum_of_reoccurring_values([1,1,2,3]) = 1
sum_of_reoccurring_data_points([1,1,2,3]) = 2
Failing build is due to the latest baseline snapshot not containing the new feature `sum_of_reoccurring_data_points`.
> New feature calculator: Sum of reoccurring data points

- tsfresh/__init__.py
- tsfresh/feature_extraction/extraction.py
New pull request for issue #147. 
The user can then specify the log level by something like: 
```import logging```
```logging.basicConfig(level=logging.INFO)```
> Fix for issue 147 - no handler warning

- tsfresh/feature_extraction/extraction.py
This would be the easiest solution to move the imputing out of the loops where the id chunks are aggregated.
What do you think?
> moved imputing out of the loop

- tests/examples/test_robot_execution_failures.py
- tests/feature_extraction/test_extraction.py
- tests/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/extraction.py
- tsfresh/feature_extraction/feature_calculators.py
This one was some major work, so let me describe everything in detail:
I have done some profiling to increase the runtime performance of the feature extraction. 
I have done this using two tools (as reference for later): cProfile + pyprof2calltree for vizualisation and kernprof (from line_profiling), e.g. with
python -m cProfile -o prof.out tests/examples/test_robot_execution_failures.py
pyprof2calltree -i prof.out -k
kernprof -l -v tests/examples/test_robot_execution_failures.py
Everything was done on our default robots failures dataset (I know that this may not be the perfect example for out usage, but I need to use something that is standardized).
After identifying the main runtime issues, I have refactored them step by step. I have made sure, that the results stayed the same during …
> Make extraction faster

- notebooks/human_activity_recognition_multi_class_example.ipynb
hi, i noticed in the latest version of tsfresh you use the new method of passing in your impute function to `extract_features` instead of setting it in the `extraction_settings`. So I updated the notebook so others would see this (it tripped me up for a bit, as I was wondering why my data wasn't being imputed).
let me know if there's anything else i need to do for this PR.
> update human activity notebook with new impute

- tests/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_extraction/settings.py
I ditched the "max_lag" as it truncated the input.
I added some unit tests and updated the documentation
See issue #228 for a detailed discussion
> Fix the trunction bug for fft_coefficients

- notebooks/human_activity_recognition_multi_class_example.ipynb
sorry, just tried running the notebook and realized i need to get rid of the newline and comma after deleting the line as well.
that's what i get for editing the ipynb file in vim
> fix extra newline in human activity recognition notebook

- tests/utilities/test_dataframe_functions.py
- tsfresh/utilities/dataframe_functions.py
This fixes both a unittest, which was wrong (and had the same problem as the bug in our impute function) and the impute function itself.
Also, it speeds up the impute by a large amount (using more memory though) - it is basically calculated in notime now.
This should fix #272.
> Fix impute

- tests/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
* I was mistaken, there are already unit tests for auto-
correlation
* pd.Series.autocorr() and statsmodels.tsa.stattools.acf yield
different results
* autocorrelation now mimics the "acf" behaviour, but calculates
a single lag and not all lags up to the specified one
* The calulation coincides now with the formula at
https://en.wikipedia.org/wiki/Autocorrelation#Estimation
* Added some tests
> Change autocorrelation feature calculator (#273)

- tests/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_extraction/settings.py
* The PACF can be used to determine the lag p of an AR(p) process
* Comprehensive docstring
* Many tests added. Some may be discarded
* Use the option `method="ld"` which is fastest and does not throw
Singular Matrix Errors compared to "yw"
* The OLS method is buggy / wrong (see statsmodels issue #3839)
* Solves tsfresh issue #223
> Add partial autocorrelation feature calculator

- docs/_templates/module_functions_template.rst
- docs/conf.py
- docs/index.rst
- docs/text/feature_calculation.rst
- docs/text/list_of_features.rst
* I did not go for a new file list_of_features.rst but included
it in the already present feature_calculation.rst to avoid
duplicates
* The list of functions is autogenerated
* It is accessible from the sidebar, but when you click on it, the
sidebar collapses (try it out!)
* the files are autogenerated in the _generate folder (no need for
version control)
* See also issue #285
> Add list of feature_calculators with sphinx autosummary extension

- tests/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
The aforementioned feature extractor would put `attr_usedlag` in the column title, causing `get_config_from_string` to parse the attribute correctly. Added quotes like in the FFT feature extractor to fix this, so the resulting column title should be `attr_"usedlag"` instead.
> Bugfix - augmented Dickey-Fuller feature extractor improperly quoted parameter

- README.md
- binder/generate_binder_requirements.py
- binder/requirements.txt
This is a quick PR to add some pieces necessary to allow the examples in this repo to run on `mybinder.org`. This would make it possible for people to run your example notebooks interactively in the cloud by clicking on the badge in your README (or just going to the URL).
Basically all I did was copy over your requirements.txt file to a `binder` folder and added a few extra dependencies that were called from the notebooks (including the `tsfresh` library itself). Let me know if there's another way you'd prefer to handle dependencies, or if you have other questions in general. I think it'd be useful for people to be able to run the examples interactively without installing `tsfresh` / dependencies on their own machine!
Here's what would happen if people go to the binder-version of this …
> adding binder requirements + badge

- .travis.yml
- tests/integrations/test_notebooks.py
- Set default_timeout = 900 and passing through to each notebook test
- Also includes a commented out section to disable notebook tests on Travis if
this is desired at any point in the future.
Modified:
tests/integrations/test_notebooks.py
> increase-timeouts-notebook-tests #409

- requirements.txt
- tests/fixtures.py
- tests/units/feature_extraction/test_extraction.py
- tsfresh/feature_extraction/extraction.py
The added tests show a problem where DataFrame indices are converted to float if they are "nearly" floats. The test case uses indices with the format 99999_9999_99. A small change to fix this. Thanks for the great library.
> fix for index preservation and test cases.

- tests/integrations/test_notebooks.py
On the developer machine the ``os.environ['TRAVIS']`` environment variable does not exist and local tests fail, related to increase-timeouts-notebook-tests #409 #410
> Wrap TRAVIS os.environ in try except

- notebooks/timeseries_forecasting_basic_example.ipynb
- notebooks/visualize-benjamini-yekutieli-procedure.ipynb
- tests/integrations/test_notebooks.py
- tests/units/scripts/test_run_tsfresh.py
Changelog:
* Fix a couple of **PermissionError** under WinNT operating systems
* Update the Benjamini-Yekutieli notebook to use **calculate_relevance_table()** instead of the deprecated **check_fs_sig_bh()**
* Update the Time Series Basic Example notebook to feed the **AdaBoostClassifier predict()** method correctly
> Fix errors in the tests

- tsfresh/feature_selection/benjamini_hochberg_test.py
This is the first of a series of performance improvements to make `tsfresh` work faster. I will not change anything structurally and will try to keep the code as close to the original as possible.
Changelog:
* Vectorize the `benjamini_hochberg_test()` function using the `numpy` package. (We already have it as dependency anyway.)
> Use numpy for faster performance of Benjamini Hochberg

- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
Changelog:
* Added new `_roll(a, shift)` method which uses `numpy.concatenate()` to reduce the overhead of `numpy.roll()` limiting the use to 1D arrays only.
Benchmark example:
```
%timeit numpy.roll(x, shift=5)
27.2 µs ± 713 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit _roll(x, shift=5)
10.6 µs ± 309 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
> Improve rolling using numpy concatenate

- tsfresh/feature_selection/significance_tests.py
Changelog:
* Changed all **pandas.Series** methods in the significance tests to **numpy** methods which are faster (see below).
Benchmark example:
```
%timeit x.isnull().any()
573 µs ± 20.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
%timeit numpy.isnan(x.values).any()
15.8 µs ± 418 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
> Use numpy for better performance of significance tests

- tsfresh/feature_selection/benjamini_hochberg_test.py
np.sum sums all elements and presents a scalar C. Scalar C is then applied across the full range of K to form T. Tested it to make sure it didn't affect the use of T to compare p-values and determine relevance.
> switch to scalar sum when features are not all independent

- tsfresh/transformers/relevant_feature_augmenter.py
Addresses #537 by moving side effects in RelevantFeatureAugmenter from the constructor to the `fit()` function, which allows scikit-learn to clone the transformer. Transformer cloning is necessary for cross-validation and grid search functionality in sklearn.
This enables the following simple example to run:
```python
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from tsfresh.examples import load_robot_execution_failures
from tsfresh.transformers import RelevantFeatureAugmenter
df_ts, y = load_robot_execution_failures()
X = pd.DataFrame(index=y.index)
augmenter = RelevantFeatureAugmenter(column_id='id', column_sort='time', timeseries_container=df_ts)
pipeline = Pipeline([('augmenter', …
```
> Refactor RelevantFeatureAugmenter to enable cloning

- tests/units/utilities/test_dataframe_functions.py
- tsfresh/utilities/dataframe_functions.py
When using tsfresh with batched df input without column_value or column_kind specified, tsfresh will automatically convert it to the required melted format in _normalize_input_to_internal_representation.
However, the pd.melt() function works differently than the code assumes. If the column_sort contains many various types of indices that do not overlap, this results in wrong input data, resulting in incorrect input data for feature generation!
Reasoning: pd.melt() does not interleave per-ID series, it stacks them. Therefore, when assigning back the column_sort, the column_sort needs to be tiled, not repeated.
> Fix indexing of melted normalized input

- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
Use less and greater operators instead of less-or-equal and greater-or-equal operators in `longest_strike_below_mean` and `longest_strike_above_mean` to fix issue #577. I additionally added a few more test cases on this corner case.
> Fix off-by-one error in longest strike features (fixes #577)

- tsfresh/feature_extraction/feature_calculators.py
According to #529, np.arange(4096)**3 overflows on Windows 10 because
dtype is set to int32.  Specify dtype=float to avoid overflows.
> ensure that get_moment() uses float computations

- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
This uses a simpler formula for calculating `mean_change` that was already proposed in #542. The proof for this simplification follows. Moreover, I fixed the documentation, because we actually divide by `n - 1` because a series with `n` elements only has `n - 1` differences. I also added a few test cases to check some corner cases.
> Optimize mean_change (fixes issue #542) and correct documentation

- CHANGES.rst
- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
The `change_quantiles` function need to sum the bool index array. Currently it's using the builtin `sum` function. However, NumPys `np.sum` will be faster on arrays.
I ran some test on it.
```python
import timeit
stmt = """change_quantiles(np.random.rand(300000) * 1000, 0.1, 0.2, False, 'mean')"""
print(timeit.timeit(stmt=stmt, setup='import numpy as np;from tsfresh.feature_extraction.feature_calculators import change_quantiles', number=1))
```
With the builtin `sum` function it takes 0.5s, while NumPys `np.sum` takes only 0.02s.
> Improve performance with Numpy's sum function

- tsfresh/feature_extraction/feature_calculators.py
This ensures that _do_extraction_on_chunk will pass a Series argument
and not a Numpy array, and avoids a Series->ndarray->Series conversion.
> add @set_property("input", "pd.Series") when needed

- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_extraction/settings.py
- tsfresh/utilities/dataframe_functions.py
This pull request fixes #494, remove all DeprecationWarning and FutureWarning raised by tsfresh itself when running tests.
> Remove warnings

- tsfresh/feature_extraction/feature_calculators.py
This is similar to #542, mean_second_derivative_central has a simpler formula.
Also fix its docstring as had been done in #574.
> Optimize mean_second_derivative_central

- tsfresh/utilities/dataframe_functions.py
Hello,
This PR solves #557.  The support for  index based features introduced in tsfresh 0.12.0 only works when `column_kind` and `column_value` are passed to `extract_features()`. 
Here is an example of the issue:
```python
import pandas as pd
from tsfresh.feature_extraction import extract_features
from tsfresh.feature_extraction.settings import TimeBasedFCParameters  
df = pd.DataFrame({"id": ["a", "a", "a", "a", "b", "b", "b", "b"], 
"value": [1, 2, 3, 1, 3, 1, 0, 8],
"kind": ["temperature", "temperature", "pressure", "pressure",
"temperature", "temperature", "pressure", "pressure"]})
extracted = extract_features(df, column_id="id", column_value='value', column_kind='kind',
default_fc_parameters=TimeBasedFCParameters())
extracted.info()
#> <class 'pandas.core.frame.DataFrame'>
#> …
```
> Preserve index when column_value and column_kind not provided

- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_extraction/settings.py
Since 'raise' keyword was missing from this block:
if ql >= qh:
ValueError("ql={} should be lower than qh={}".format(ql, qh))
this test did nothing and 0 was returned after some computations.
Modify ComprehensiveFCParameters["change_quantiles"] to only consider parameters with ql < qh.
> Early return from change_quantiles if ql >= qh

- tests/units/utilities/test_dataframe_functions.py
- tsfresh/utilities/dataframe_functions.py
> Added a check for wrong column names and a test for this check

- tsfresh/feature_extraction/feature_calculators.py
There was a logic error in both functions, innermost dictionary did only contain a single element.
Moreover in agg_linear_trend, _aggregate_on_chunks was called even if result is cached.
> Fix cache in friedrich_coefficients and agg_linear_trend

- tsfresh/feature_extraction/feature_calculators.py
There were two issues:
* sum index should start from 1 and not 0
* x[i+2*lag] should not be squared
Fix #585.
> Fix docstring of c3

- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
The result of Augumented Dickey-Fuller test deeply depends on how we
choose the lag parameter. StatsModels' adfuller() function provides
several criteria for that selection (AIC, BIC and t-stats etc).
This makes it a parameter, and enables users to tweak the lag selection
according to their preference.
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>
> Add "autolag" parameter to augmented_dickey_fuller()

- tests/units/feature_selection/test_relevance.py
- tsfresh/convenience/relevant_extraction.py
- tsfresh/feature_extraction/extraction.py
- tsfresh/feature_selection/relevance.py
- tsfresh/feature_selection/selection.py
- tsfresh/feature_selection/significance_tests.py
- tsfresh/transformers/feature_augmenter.py
- tsfresh/transformers/relevant_feature_augmenter.py
- tsfresh/utilities/dataframe_functions.py
- tsfresh/utilities/distribution.py
On Windows, multiprocessing creates new environments, and thus state of warnings module must be initialized by all workers.
Fix #518.
Fix #559.
May also help with #557 and #604.
Remove a pandas warning about result.columns.contains("value").
Add show_warnings option to select_features and extract_relevant_features.
Replace _logger.warning() calls by warnings.warn() so that warnings are disabled when warnings.simplefilter("ignore") has been called.
These warnings are annoying inside Jupyter notebooks, they produce lots of output and cause trouble.
Also add this option in calculate_relevance_table, and prints a single warning with the list of constant features instead of lots of warnings.
> Fix filtering on warnings with multiprocessing on Windows

- .travis.yml
- requirements.txt
- tsfresh/feature_extraction/feature_calculators.py
New statsmodels 0.11.0 package seems to cause compatibility issues with older packages:
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
We depend on statsmodels 0.9.0 because this is the first version available on conda
for Python 3.5, 3.6 and 3.7, but users can use 0.8.0 as well.
Fix `ar_coefficient method` with newest statsmodels, `AR` class is now immutable.
Also latest dask requires fsspec in order to read data from disk.
> Add a versioned dependency on statsmodels for travis CI

- docs/_static/theme_override.css
- docs/conf.py
following the idea of https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html
That should solve #636.
> Add wrap to tables

- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
Added coefficient of variation to have a relative value for standard deviation.
variation_coefficient = np.std(X) / np.mean(X)
Main problem is that we cannot compute the variable when the mean is 0, I chose to return missing value in this case.
> Added variation coefficient

- tsfresh/feature_selection/relevance.py
- tsfresh/feature_selection/selection.py
> Fix documentation. 

- tsfresh/transformers/relevant_feature_augmenter.py
I am working on some datasets where the feature extraction step is very time consuming, sometimes totaling multiple days when running a suite of experiments. I'm using `RelevantFeatureAugmenter` in a scikit-learn `Pipeline` object, and noticed that the training features are extracted twice, because `fit()` extracts them once and `transform()` re-extracts a subset of them (the relevant ones). I see why this is needed, since `fit()` and `transform()` need to be independent for the sake of re-applying the transformer to new data.
However, in a scikit-learn pipeline, `fit_transform()` is called during training since the two steps are sequential. For these situations, I added a `fit_transform()` function which avoids re-extracting the relevant features.
I created a small simulated dataset to …
> Optimize RelevantFeatureAugmenter to avoid re-extraction

- CHANGES.rst
- tests/units/utilities/test_dataframe_functions.py
- tsfresh/utilities/dataframe_functions.py
> Add add_sub_time_series_index

- CHANGES.rst
- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_extraction/settings.py
Following the description in https://en.wikipedia.org/wiki/Lempel-Ziv_complexity
> Implemented two new feature calculator: Lempel Ziv complexity and Fourier Entropy

- CHANGES.rst
- tests/units/transformers/test_feature_augmenter.py
- tests/units/transformers/test_relevant_feature_augmenter.py
- tsfresh/transformers/feature_augmenter.py
- tsfresh/utilities/dataframe_functions.py
Following the discussion in #524 we have to make sure that the ids present in the time series container and the given index have at least something in common (otherwise it makes no sense).
@JacquesDonnelly that should have prevented at least your problem!
> Prevent wrong indices in the passed time series container

- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
Hi,
I have been using tsfresh for about 2 months, one attribute that came up to my mind in my cases is to use the deviation from Newcomb-Benford distribution, specifically the correlation between a data array and the expected distribution.
Newcomb-Benford distribution considers a log distribution of the first digits from data.
This analysis has been used for fraud and anomaly detection. More uses - https://scholar.google.com/scholar?q=benford+law+time+series
_This is my first pull request to a major package, please if anything is wrong, please let me know._
> Created benford_correlation(x) function

- CHANGES.rst
- tsfresh/convenience/bindings.py
After the pivoting was speed up in #705,
the helper function for the spark and dask bindings also needs to
change.
Additionally, this allows to introduce a fix for #709.
> Fix bindings helper function

- CHANGES.rst
- tests/integrations/examples/test_driftbif_simulation.py
- tests/units/feature_selection/test_relevance.py
- tsfresh/feature_selection/relevance.py
- tsfresh/feature_selection/selection.py
- tsfresh/feature_selection/significance_tests.py
This looks like a quite large bug to me. 
In principle, X and y could have the same index entries (what we check), but we never check if the order is the same! So passing in a `X` with index `[0, 1, 2]` and a `y` with index `[2, 1, 0]` will not raise any problems.
For classification tasks, this is not a problem, as all the significance tests except `target_real_feature_real_test` do not care about the order of the index, as `x` and `y` are re-ordered internally again in all the other tasks. But for `target_real_feature_real_test` the index is stripped before any re-order could happen - which leads to the bug described in #713.
This PR fixes this. I am a bit puzzled why this was never a problem before :-/ 
Therefore I added the exact test from the issue, to see any degradation again. …
> Make sure X and y are sorted equally in select_features

- CHANGES.rst
- tests/integrations/test_bindings.py
- tsfresh/convenience/bindings.py
I added a test for the dask bindings. Testing spark is hard, as we would need to install spark first.
This is definitely not impossible, but I think for now the dask test should be enough first.
> Fix bindings

- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
As per issue #724 (https://github.com/blue-yonder/tsfresh/issues/724).
percentage_of_reoccurring_datapoints_to_all_datapoints is actually percentage_of_reoccurring_values_to_all_values implementation and vice versa .
> swapped function names for percentage of reoccuring

- .github/workflows/test.yml
- .github/workflows/test_all.yml
- CHANGES.rst
- README.md
- test-requirements.txt
I moved from coveralls to codecov, as it has better support for forked branches (to help solving https://github.com/blue-yonder/tsfresh/issues/732) and because it has a nicer UI ;-)
> Change the coveralls github action to fix missing coveralls in PRs

- CHANGES.rst
- tests/units/utilities/test_dataframe_functions.py
That should remove a failure which comes up in newer pandas versions because the testing is more strict.
> Fix test failure with newer pandas version

- tsfresh/feature_extraction/feature_calculators.py
As described in https://github.com/statsmodels/statsmodels/pull/6846, PACF limits lag length to 50% of sample size, this PR follows the behavior to make it works well with the latest statsmodels version.
Fixes #748 if merged.
> Fix the failure with the latest statsmodels installed

- CHANGES.rst
- docs/text/forecasting.rst
- tests/units/utilities/test_dataframe_functions.py
- tsfresh/utilities/dataframe_functions.py
> Allow arbitrary rolling sizes

- tsfresh/feature_selection/relevance.py
Is the style and wording good like this?
> Improve relevance table function documentation

- requirements.txt
- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_extraction/settings.py
@nils-braun @tylerwmarrs let me know what you think!
> Addition of matrix_profile feature

- docs/text/faq.rst
- docs/text/feature_extraction_settings.rst
- docs/text/how_to_contribute.rst
- docs/text/large_data.rst
- docs/text/tsfresh_on_a_cluster.rst
- tsfresh/convenience/relevant_extraction.py
- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_selection/relevance.py
- tsfresh/feature_selection/selection.py
- tsfresh/transformers/feature_selector.py
- tsfresh/transformers/relevant_feature_augmenter.py
- tsfresh/utilities/dataframe_functions.py
- tsfresh/utilities/distribution.py
Fixes a few minor typos (spelling mistakes and a formatting problem) in the documentation.
> Fix minor typos in the docs

- .gitignore
exclude file from git which are produced by testing and building the docs
.lock files
.coverage. files
> Add unwanted filetypes to gitignore

- tsfresh/feature_extraction/extraction.py
- tsfresh/transformers/feature_augmenter.py
> Fix imputing docu

- CHANGES.rst
- tests/units/feature_extraction/test_extraction.py
- tsfresh/feature_extraction/extraction.py
- tsfresh/feature_selection/relevance.py
- tsfresh/utilities/dataframe_functions.py
After several months away from TSFRESH, I updated to the latest version and encountered some very length error messages. It seemed like the messages were due to multiprocessing, so I set `n_jobs` in `RelevantFeatureAugmentor` to 1 thinking that would fix it by forcing single processing. It didn't fix it, and after some docs reading I discovered `n_jobs=0` is actually the way to force single processing. This is a bit un-intuitive, I think. This pull request changes the behavior so `n_jobs=1` will have the same behavior as `n_jobs=0`.
There might be a good reason why `n_jobs=1` should spawn multiprocessing, but this would have saved me a lot of debugging so I thought I'd suggest it.
On an aside, I should probably also figure out why multiprocessing was causing problems, but that's for …
> Enable multiprocessing only for n_jobs > 1

- docs/text/faq.rst
- docs/text/introduction.rst
Adds paragraphs to intro and faq in docs to further clarify that tsfresh only uses timestamp for ordering, not time intervals.
> Docs regarding irregular time series 

- tsfresh/feature_extraction/feature_calculators.py
Mean absolute change is over the differences of consecutive values, so the denominator should be `n-1`, not `n`. Numpy `diff` confirms this, e.g.
```
>>> x = np.array([1, 2, 4, 7, 0])
>>> np.diff(x)
array([ 1,  2,  3, -7])
```
> Fix denominator in docstring for mean_abs_change

- docs/text/quick_start.rst
- tests/integrations/test_notebooks.py
Hi there 👋 
The commit 357cf3274b2d2a175e05cb7f9e40d63ae4b8a34a moved all basic examples into the root notebook folder.
References to these notebooks weren't changed yet, leading to an error 404 when clicking on the link from the quick start guide. This PR simply replaces all usages of `notebooks/examples/` with `notebooks/`.
> Fix file paths after example notebooks were moved

- install_requirements.sh
- optional-requirements.txt
- requirements.txt
- setup.py
- tests/units/feature_extraction/test_feature_calculations.py
- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_extraction/settings.py
There are many issues regarding matrixprofile not being supported anymore:
https://github.com/blue-yonder/tsfresh/issues/972
https://github.com/blue-yonder/tsfresh/issues/937
https://github.com/blue-yonder/tsfresh/issues/952
https://github.com/blue-yonder/tsfresh/issues/932
These are all related to the outdated dependency matrixprofile.
This draft MR introduces matrix profile as an optional dependency. It also makes sure many users can run this code in newer versions of python or different cpus.
Could any maintainer take a look?
> Add matrix profile as an optional import.

- tsfresh/feature_selection/significance_tests.py
The current implementation of checking the index of x and y is very unefficient for large data. Using the Panda function Index.equals solves this.
> Use pandas Index.equals in check_if_pandas_series

- tests/units/utilities/test_distribution.py
- tsfresh/utilities/profiling.py
When profiling specific functions, it is often helpful to have more fine-grained control over the `N_PROCESSES` constant used in multiprocessing. 
Getter and setter functions for the `N_PROCESSES` constant found with the other default constants.
> View and Set N Jobs

- docs/text/faq.rst
- docs/text/tsfresh_on_a_cluster.rst
Setting a few environment variables can greatly improve parallelization by removing over-provisioning. I have updated the document section discussing parallelization to show how this can be achieved.
> Extra notes on parallelization efficiencies

- docs/text/quick_start.rst
- setup.cfg
Addresses https://github.com/blue-yonder/tsfresh/discussions/1060.
Dask was de facto optional already (see the guarded import in `tsfresh/feature_extraction/data.py`), but before this PR it was installed by default.
Distributed is imported only to support Dask, when the classes `ClusterDaskDistribution` or `LocalDaskDistribution` are used, so it is not needed if Dask is not imported.
To install tsfresh with those dependencies, one can do:
pip install -e ".[dask]"
~This is needed, for example, to run the test suite.~ The documentation has been updated accordingly.
> Make Dask and Distributed optional dependencies

- tsfresh/feature_extraction/feature_calculators.py
Corrected docstrings of fctype=combiner feature calculators to have the correct return type.
Resolves #1062
> Issue #1062: Feature calculator return type documentation

- tests/units/feature_extraction/test_data.py
- tests/units/feature_extraction/test_feature_calculations.py
- tests/units/feature_extraction/test_settings.py
- tests/units/feature_selection/test_checks.py
- tests/units/transformers/test_per_column_imputer.py
- tests/units/utilities/test_dataframe_functions.py
- tsfresh/feature_extraction/feature_calculators.py
- tsfresh/feature_selection/relevance.py
- tsfresh/utilities/dataframe_functions.py
- tsfresh/utilities/string_manipulation.py
A few names have changed with bumpy 2.0. Adjust for this (as they are all backwards compatible)
> Fix code and tests for numpy >= 2.0

- tsfresh/convenience/relevant_extraction.py
`extract_relevant_features` did previously not pass `chunksize` to `extract_features`, but only to `select_features`
> extract_revant_features now passes chunksize to extract_features

- notebooks/02 sklearn Pipeline.ipynb
Noticed a few misspellings. I hope I’m not taking up valuable time by submitting this PR :).
There were a couple places I wasn’t sure what the intended meaning was, so I did not try to fix those, but would like to call them out below:
under **Prediction**:
> During interference, the augmenter does only extract the relevant features it has found out in the training phase and the classifier predicts the target using these features.
- Was “interference” intended to be used here? I’m new to tsfresh and to machine learning in general, but I was thinking this sounded off.
- To my ears the “does only” is a little awkward, and the rest of the sentence with “and the classifier” sounds like a run-off sentence.
under **Separating the time series data containers**:
> During training, only the data …
> Fix spelling/grammar in pipeline notebook

- .gitignore
- docs/text/how_to_contribute.rst
- setup.cfg
This PR adds functionality to be able to locally test multiple versions of python using `tox.`
This PR will run the test suite for python versions 3.7, 3.8, 3.9, 3.10, and 3.11 for whichever platform the user runs the tests on. The specific microversion of python depends on what is installed on the user's machine. 
`tox` will skip over running the test suite for a given version if it cannot find a particular python environment.
To test on multiple python versions, edit `envlist` in `setup.cfg` to include the python versions you want to test on, and then run:
```bash
tox -r
``` 
in the top-level directory for tsfresh. Currently the versions being tested span between python 3.7-3.11
This PR will make it much easier to (locally) test tsfresh against multiple versions of python, for a given …
> Added functionality to test multiple versions of python using tox

- .pre-commit-config.yaml
- Dockerfile.testing
- Makefile
- docs/text/how_to_contribute.rst
Related: https://github.com/blue-yonder/tsfresh/pull/994. 
Easiest to go commit by commit. Uses 3 "flows"
(1) **Test locally on specific python version** Is useful for quick iteration.
(2) **Test locally on the discoverable python versions** Is a useful sanity check for ensuring new development works on multiple versions of python. 
(3) **Test in dedicated testing environment with guaranteed availability of python versions** Is a good final sanity check. Takes longer, but creates a reproducible environment to test off and is a good 'source of truth'.
Testing time for one version is ~1 min. Note this includes the speedup from cached packages
Testing time across versions 3.7-3.11 is ~4 mins, but note that this speedup includes the speedup from cached packages.
Also note that python 3.7 …
> Dockerise testing for dev

- .github/workflows/test.yml
- setup.cfg
Drop support for deprecated python version 3.7 an 3.8.
Also, add tests for 3.10-3.12.
Until #1097 is in, constrain the version of scipy to make the CI/CD still work.
> Drop old versions of python

- Makefile
Add Git Bisect Helper to Automate Regression Debugging.
During the process of feature development not part of this PR, I used git bisect` to help identify the commit that introduced a bug (the bug in question was caused by a variable name clashing with a function name).
Adding this git bisect helper to the main line as it has a great impact on automated bug finding (when the commits are atomic).
> Add bisect debug helper

- .github/workflows/benchmark_default_branch.yml
One thing left from the recent change to drop old python versions.
> Fix python version used in benchmark

- Makefile
- setup.cfg
PR updates setup.cfg to reflect the fact that tsfresh no longer targets < 3.9. See https://github.com/blue-yonder/tsfresh/commit/d66fc0fdfe3db9c3ac50594878367da03e113c83 for context.
PR also explicitly adds targeting of python 3.12
> Bump version support

- setup.cfg
- tsfresh/feature_extraction/feature_calculators.py
https://github.com/blue-yonder/tsfresh/discussions/1096
> use PyWavelet for CWT
