docs/text/quick_start.rst
tsfresh/feature_selection/significance_tests.py

I25 fix quickstart documentation

---

tests/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

Information about this algorithm : [Approximate Entropy](https://en.wikipedia.org/wiki/Approximate_entropy) 
Also see [this](https://www.ncbi.nlm.nih.gov/pubmed/10843903?dopt=Abstract) paper for some limtations and similar algorithms which could also be implemented as a new feature in tsfresh.

Implement approximate entropy algorithm

---

scripts/run_tsfresh.py

To highlight key points of the script and handle saving the output file to any user specified path.

More informative docstring

---

docs/text/quick_start.rst

Updated the Dive in section to include the download_robot_execution_failures function as reported in #62

Update the Quick Start #62

---

scripts/run_tsfresh.py

This removes the only sample the first 50 logic and adds the required iloc referenced in https://github.com/blue-yonder/tsfresh/pull/63

run_tsfresh.py - remove sample first 50 only

---

tests/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py

Added four new features concerning doubled values.

---

tests/feature_extraction/test_settings.py
tsfresh/feature_extraction/__init__.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

This is a first draft for #21 open for discussion.

Minimal feature extractor settings

---

tests/feature_extraction/test_feature_calculations.py
tests/feature_extraction/test_settings.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

@MaxBenChrist one more try wrt https://github.com/blue-yonder/tsfresh/issues/50! made a couple of modifications per your comments (xrange/range, 1d arrays, etc...)

Sampleentropy

---

.coveragerc
tests/examples/test_har_dataset.py
tests/examples/test_robot_execution_failures.py
tests/feature_extraction/test_ts_features.py
tests/feature_selection/test_selection.py
tests/test_relevant_feature_extraction.py
tests/utilities/test_dataframe_functions.py
tsfresh/examples/har_dataset.py
tsfresh/examples/robot_execution_failures.py
tsfresh/feature_extraction/extraction.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_selection/selection.py
tsfresh/utilities/profiling.py

I will add later:
-Testcase for HAR Dataset (when archive.ics.uci.edu is up again)

Increase coverage

---

.travis.yml
tests/feature_selection/test_feature_selectors.py
tsfresh/feature_selection/feature_selector.py
tsfresh/feature_selection/settings.py

Parallel p values

---

tsfresh/feature_extraction/extraction.py
tsfresh/feature_selection/feature_selector.py

Wait for the worker processes to exit

---

tsfresh/feature_extraction/extraction.py
tsfresh/feature_extraction/settings.py

... to dismiss all warnings during extraction.
Fixing #89

Introduced a new settings parameter ... 

---

docs/index.rst
docs/text/feature_calculation.rst

and added link to feature_calculators submodule
solves #102

renamed feature_namig to feature_calculation module

---

tests/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py

check if coeff are out of cwt range

---

tsfresh/examples/har_dataset.py

... and not for the top folder to download the files.
Should solve #113

Check for the UCI dataset

---

requirements.txt
tsfresh/feature_extraction/extraction.py
tsfresh/feature_extraction/settings.py

For this, I had to change quite some things:
* I added tqdm to the requirements, as we use this for drawing the progress bar
* I had to change each parallel map to an imap, as I need to know immediately, if and when a new result is there (otherwise the function will only continue, when all results are there)
* imap needs a proper chunksize - so I copied the calculation from the multiprocessing.map function
* The result getting had to be wrapped with a tqdm. In case of per_kind this is easy - in case of per_sample this needed some more code...
This should solve #88

Added a progress bar to the feature extraction.

---

tests/feature_extraction/test_settings.py
tsfresh/feature_extraction/__init__.py
tsfresh/feature_extraction/settings.py

please do not merge this yet. there are still some unit tests missing for the ReasonableFeatureExtractionSettings object.
this will fix the failing unit tests, the build error and issue #122

added ReasonableFeatureExtractionSettings

---

tests/test_relevant_feature_extraction.py
tsfresh/feature_extraction/extraction.py

fdc is an unrelated bugfix
794 seems right to me
bb2 should improve speed on large data sets
Any comments?

Improve parallelization (once more)

---

tests/examples/test_driftbif_simulation.py
tsfresh/examples/driftbif_simulation.py

Also parameters were adapted and documentation improved. More tests were added.

Added sample ratio to driftbif simulation

---

notebooks/pipeline_with_two_datasets.ipynb

Add a notebook demonstrating how to use pipeline with 2 datasets (issue #153)

---

tsfresh/utilities/dataframe_functions.py

we do not need index for internal representation

---

tsfresh/feature_extraction/feature_calculators.py

this will fix issue 169
@kempa-liehr : regarding the polynomial fit on signal and delta , is there another way that comes to your mind then dropping nans?

fitting of polynomial on NaNs does not make sense

---

tests/utilities/test_dataframe_functions.py
tsfresh/utilities/dataframe_functions.py

Maximum rolling

---

docs/text/faq.rst

Explain how to use tsfresh with windows. I know, it's ugly.

FAQ: How to use tsfresh with windows

---

tests/feature_extraction/test_feature_calculations.py

included unit test for num_cwt_peaks function.

include unit test for num_cwt_peaks

---

docs/text/faq.rst
docs/text/feature_extraction_settings.rst

I polished the documentation about the new settings api. Further, I also mentioned the `from_columns` method

Polish docs

---

tests/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

I added a feature that captures characteristics about the overall trend. 
It fits a linear regression model and returns characteristics of it such as slope or intercept.

Trend features

---

tests/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

Feature implementation by Max, I have only fixed a problem ;-)

Agg trend features

---

docs/text/rolling.rst

Hi everyone,
as mentioned in #197 and #174, this is the PR for updating the docs of rolling (sorry for taking so long).
There is a "comment" to discuss whether the first scenario described really fits.
I hope this somehow helps and would be happy to improve this PR.

Update docs of rolling page

---

tests/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py

use acf from statsmodels to calculate mean_autocorrelation

---

.travis.yml
tests/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

I added the pvalue and the used lag as features. 
they were calculated anyway so we get more features for free. 
To implement this I had to change the type of augmented_dickey_fuller from simple to combiner

P value augmented dickey fuller

---

tests/test_notebooks.py

there was a problem with the python3 kernel when testing the notebooks. I turned the testing of the notebooks off for py3

only test nbs for py2

---

tsfresh/feature_extraction/extraction.py

possibly turn off warnings for impute function

---

tsfresh/examples/har_dataset.py
tsfresh/examples/robot_execution_failures.py

UCI has changed its citation request https://archive.ics.uci.edu/ml/citation_policy.html

Corrected URLs in references to UCI

---

tests/feature_selection/test_checks.py
tsfresh/feature_selection/significance_tests.py

I added the check and refactored the surrounding tests for clarity of intent and legibility.

Add check for nans

---

tests/utilities/test_dataframe_functions.py
tsfresh/utilities/dataframe_functions.py

use name of value column as kind

---

tests/units/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

Hi all,
As mentioned in the [Spectral Centroid PR](https://github.com/blue-yonder/tsfresh/pull/314), I decided it would be cleaner to just restart the PR.  As requested, I have added a new combiner feature called fft_aggregated.  
I added tests for it, they pass.  There are other tests that I'm not sure are related to this new feature that are not passing for me.
Best.

New Feature: fft_aggregated

---

tests/units/feature_selection/test_relevance.py
tsfresh/feature_selection/relevance.py

Warning no relevant features

---

.github/ISSUE_TEMPLATE.md

Having the traceback may help narrow down things sometimes.

Report error

---

tests/units/feature_extraction/test_settings.py
tsfresh/feature_extraction/settings.py

add columns_to_ignore parameter to from_columns

---

README.md

typo correction in readme

---

tests/units/feature_selection/test_selection.py
tsfresh/feature_selection/selection.py

warning if target vector contains only one label

---

README.md

Added DOI of published paper version

tsfresh paper has been published online

---

docs/text/quick_start.rst

Added code to generate visualization for easier reproducibility

Added code to generate visualization

---

.travis.yml
tsfresh/utilities/dataframe_functions.py

- Change tuples to list to fix #414
- Also includes the .travis.yml fix from #411
Modified:
.travis.yml
tsfresh/utilities/dataframe_functions.py

#414 pandas-group-by-tuple

---

.travis.yml

For test purposes only relating to #412

Testing numpy latest and 1.10.4 stages #412

---

docs/text/introduction.rst

Hi. This is my first PR in GitHub. Did I do everything correctly? I hope that I can contribute more from now on. : - ))
By the way, can/should I close the issue #449 ? After all, the question is now answered. I am asking that because I am new in GitHub and I noticed that the tsfresh project does not have a code of conduct.

improve documentation (#449)

---

tsfresh/feature_extraction/feature_calculators.py

its f_agg not attr for agg_autocorrelation

---

CHANGES.rst
tests/units/feature_extraction/test_feature_calculations.py
tests/units/feature_extraction/test_settings.py
tsfresh/feature_extraction/feature_calculators.py

Issue501 fix fcoefficients

---

tsfresh/feature_extraction/feature_calculators.py

Corrected small typo. Disfcovery -> Discovery

Corrected small typo. Disfcovery -> Discovery

---

tsfresh/utilities/dataframe_functions.py

fill up argument `max_timeshift` when calling function `roll_time_series`

fill up argument `max_timeshift` when calling function `roll_time_series`

---

docs/text/how_to_add_custom_feature.rst

Add the `set_property` import so users know which module it comes from for defining custom features.

Add set_property import

---

tests/units/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py

Avoid division by zero in energy_ratio_by_chunks

---

tests/units/utilities/test_dataframe_functions.py
tsfresh/utilities/dataframe_functions.py

Make sure there is at least a single column which we can use for data

---

setup.py

Make sure to not install the tests folder

---

.travis.yml

This PR builds on top of #602  with just a bit of extra refactoring. All the hard work was done by @dbarbier! 
I though it is easier to actually to the changes instead of describing it one by one :-) This is how I imagined it with the script just defined once (I also added some comments).

Refactor .travis.yml part II

---

tsfresh/feature_extraction/extraction.py

Fixing: 620 remove outdated logging config

---

CHANGES.rst

formatted CHANGES.rst

---

tests/units/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

I created two simple features, which I needed for my project. These features return the percentage of values in a time series that are above/below a certain threshold.

Add count_above and count_below features

---

tsfresh/feature_extraction/feature_calculators.py

Make sure to always have a tuple. 

---

tests/units/utilities/test_distribution.py

I disabled the test to make travis work again.

It seems dask is not working with python 3.5 well anymore

---

docs/text/how_to_add_custom_feature.rst

That fixes https://github.com/blue-yonder/tsfresh/issues/517

Added the datetimeindex explanaition from the notebook to the docs

---

tsfresh/feature_extraction/settings.py

Increase the extracted ar coefficients to all - which makes more sense

---

docs/text/sklearn_transformers.rst

Fix documentation example

---

docs/text/introduction.rst

Added reference. 

---

tests/integrations/test_full_pipeline.py
tests/units/feature_extraction/test_extraction.py
tests/units/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py

Superseeds #641 and adds tests.
Thanks to @trueckel for the implementation.

Fix parameter sorting

---

tsfresh/feature_extraction/feature_calculators.py

Improved documentation

---

docs/index.rst
docs/text/data_formats.rst
docs/text/forecasting.rst
docs/text/introduction.rst
docs/text/list_of_features.rst
docs/text/tsfresh_on_a_cluster.rst
tsfresh/convenience/relevant_extraction.py
tsfresh/feature_extraction/extraction.py
tsfresh/feature_extraction/feature_calculators.py

Just some small docu fixes :-)

Docu fixes

---

CHANGES.rst
README.md
docs/conf.py
docs/images/tsfresh_logo.svg
docs/images/tsfresh_new_logo.svg
docs/index.rst
docs/text/quick_start.rst

Thanks to @kohlrabi90 for helping out :-)

New tsfresh logo!

---

.github/workflows/benchmark.yml
.github/workflows/benchmark_default_branch.yml
CHANGES.rst
setup.cfg
test-requirements.txt
tests/benchmark.py

As we are currently talking a lot about performance, I added some benchmarks.
They are also automatically shown here: https://blue-yonder.github.io/tsfresh/dev/bench/ (which is currently of course still a bit empty)

Add benchmarking test

---

tsfresh/feature_extraction/data.py

@hoesler I included your comments from the PR (which I, unfortunately, closed too early...)

Include comments from #722

---

CHANGES.rst
tsfresh/feature_extraction/feature_calculators.py

Added the changes I suggested in the issue.

Closes #743

---

notebooks/examples/05 Timeseries Forecasting.ipynb

Fixing typos in notebook.

---

CHANGES.rst
tests/units/utilities/test_dataframe_functions.py
tsfresh/utilities/dataframe_functions.py

Correct output for make_forecasting_frame

---

tsfresh/feature_extraction/extraction.py

Also surpress warnings in dask

---

docs/text/how_to_add_custom_feature.rst

Fixed minor typo from `set_propert` to `set_property`

Fixed #789 Typo in "how to add custom feature"

---

tsfresh/feature_selection/relevance.py

Fixes #747 (original code by @lonet)

Convert to the correct type on warnings

---

requirements.txt
tests/units/feature_extraction/test_feature_calculations.py
tsfresh/feature_extraction/feature_calculators.py
tsfresh/feature_extraction/settings.py

@nils-braun I've implemented all of the things that we had discussed. Would you mind taking a look and see if we're good to go?

Added new query similarity counter feature

---

.github/workflows/benchmark_default_branch.yml
.github/workflows/deploy.yml
.github/workflows/test.yml
tests/units/feature_selection/test_relevance.py
tests/units/utilities/test_dataframe_functions.py

Related to the discussion in #813

Fix build and test failures

---

docs/text/introduction.rst

streaming data → online
time series data → offline

Disambiguation issues #829

---

docs/text/how_to_add_custom_feature.rst
tsfresh/feature_extraction/feature_calculators.py

add one linear in docstring of feature calculator

---

tests/units/utilities/test_dataframe_functions.py
tsfresh/utilities/dataframe_functions.py

Allow for empty dataframes on imputing

---

docs/text/how_to_add_custom_feature.rst

Fix documentation page

---

docs/text/how_to_add_custom_feature.rst
tsfresh/feature_extraction/feature_calculators.py

Add missing space and line break for fixing system message in documentation.

Fix other bugs in documentation page (#851)

---

docs/text/data_formats.rst
docs/text/faq.rst
docs/text/feature_calculation.rst
docs/text/feature_extraction_settings.rst
docs/text/feature_filtering.rst
docs/text/forecasting.rst
docs/text/how_to_add_custom_feature.rst
docs/text/introduction.rst
docs/text/large_data.rst
docs/text/list_of_features.rst
docs/text/quick_start.rst
docs/text/sklearn_transformers.rst
docs/text/tsfresh_on_a_cluster.rst

Re words documentation throughout.
@nils-braun @MaxBenChrist @jneuff 
ready for review

re-words documentation
